### ISSUE TITLE
Rename implicit defs to avoid name clashes in companion object

### ISSUE THREAD

**Issue by jchapuis** [NeQuissimus/circe-kafka#8]
When declaring serializers as `val` in the companion object of a case class, the implicit resolution is broken due to the name clash.

Workaround is to import the library with renames `import nequi.circe.kafka.{ serializer => genSerializer, deserializer => genDeserializer, serde => genSerde }`, but I would suggest changing the names in the library as this is a hassle and the name doesn't actually matter.

**Comment by NeQuissimus** [comment]
Ah yes, makes sense. I have not run into that myself but you are correct. I have to release a Kafka 2.0.1 version anyways, I will take care of this in the coming days.
Thanks for the report.
